language: minimal

jobs:
  include:
    - name: 'Retail'
      install:
        - export GAME_VERSION="retail"

    - name: 'Classic'
      install:
        - export GAME_VERSION="classic"

    - name: 'TBC'
      install:
        - export GAME_VERSION="bc"

addons:
  apt:
    packages:
      - luarocks

before_install:
  - sudo luarocks install luacheck

script:
  - luacheck idTip.lua --no-color -q

after_success:
  - cd $TRAVIS_BUILD_DIR
  - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -g $GAME_VERSION
